# -*- coding: utf-8 -*-
"""IAIMAGEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152S9LTM5L5XsbjmoRuWdXtWpGr0c2pAK
"""

"!pip install ultralytics opencv-python matplotlib"

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import requests

useYolo = YOLO("yolov8n.pt")

url = "https://ultralytics.com/images/bus.jpg"

img_path = "imagem.jpg"
img_data = requests.get(url).content

with open(img_path, 'wb') as handler:
    handler.write(img_data)

from google.colab import drive

drive.mount('/content/drive')
#

results = useYolo(img_path)

result_img = results[0].plot()

plt.imshow(result_img)

from google.colab import files
uploded = files.upload()

for name in uploaded.keys():
  results = useYolo(name)
  result_img = results[0].plot()

  plt.imshow(result_img)
  plt.show()

"""### Implementação do Contador de Objetos

Nesta seção, vamos processar as detecções e contar quantos objetos de cada tipo foram encontrados.
"""

from collections import Counter
import cv2
import matplotlib.pyplot as plt

results = useYolo(img_path)
img_final = results[0].plot()

classes_detectadas = [results[0].names[int(cls_id)] for cls_id in results[0].boxes.cls]
contagem = Counter(classes_detectadas)

y_offset = 50
for objeto, qtd in contagem.items():
    texto = f"{objeto.capitalize()}: {qtd}"
    cv2.putText(img_final, texto, (20, y_offset),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
    y_offset += 40

print("--- Objetos Encontrados ---")
for objeto, qtd in contagem.items():
    print(f"{objeto.capitalize()}: {qtd}")

plt.figure(figsize=(10, 6))
plt.imshow(img_final)
plt.title("Contagem de Objetos")
plt.axis('off')
plt.show()

pip install face_recognition

from google.colab import files
muitagente = files.upload()
umapessoa = files.upload()